// Embed the bundled woff2 files into src/fonts.js, so the page can load its type from
// file:// (Chrome refuses @font-face URLs on file:// pages).
//
//   node tools/fonts.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const faces = [
  ["Instrument Serif", "normal", "400", "instrument-serif-latin-400-normal.woff2"],
  ["Instrument Serif", "italic", "400", "instrument-serif-latin-400-italic.woff2"],
  ["Geist Mono", "normal", "100 900", "geist-mono-latin-wght-normal.woff2"],
];

const lines = [
  "// Generated by tools/fonts.mjs from assets/fonts. Do not edit by hand.",
  "// Instrument Serif and Geist Mono, Latin subsets, SIL Open Font License 1.1.",
  "(function () {",
  "  const FM = (globalThis.FM = globalThis.FM || {});",
  "  const faces = [",
];
for (const [family, style, weight, file] of faces) {
  const data = readFileSync(resolve(ROOT, "assets/fonts", file)).toString("base64");
  lines.push(`    [${JSON.stringify(family)}, ${JSON.stringify(style)}, ${JSON.stringify(weight)}, "${data}"],`);
}
lines.push(
  "  ];",
  "  FM.fontsReady = (async function () {",
  "    if (typeof FontFace === \"undefined\" || typeof document === \"undefined\") return;",
  "    const loaded = await Promise.all(",
  "      faces.map(([family, style, weight, data]) =>",
  "        new FontFace(family, `url(data:font/woff2;base64,${data})`, { style, weight }).load(),",
  "      ),",
  "    );",
  "    for (const face of loaded) document.fonts.add(face);",
  "  })();",
  "})();",
  "",
);
writeFileSync(resolve(ROOT, "src/fonts.js"), lines.join("\n"));
console.log("wrote src/fonts.js");
